import { Inter } from 'next/font/google'
import '@/public/styles/globals.css'
import '@/public/styles/animate.css'
import '@/public/styles/bootstrap.min.css'
import '@/public/styles/font-awesome.min.css'
import '@/public/styles/ie.css'
import '@/public/styles/reset.css'
import '@/public/styles/rtl.css'
import '@/public/styles/style.css'
import '@/public/styles/theme_config.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
